import { Supplier } from "../lib/types";

export const dummyData: Supplier[] = [
  {
    id: 1,
    name: "asurjadi@ur.com updated",
    address: "Australia",
    email: "-",
    phone: "-",
  },
  {
    id: 2,
    name: "darragh@shotcreteaustralia.com.au",
    address: "Australia",
    email: "-",
    phone: "-",
  },
  {
    id: 3,
    name: "Credit Officer 2 9485 4059",
    address: "Australia",
    email: "-",
    phone: "-",
  },
  { id: 4, name: "Test", address: "Australia", email: "-", phone: "-" },
  { id: 5, name: "11", address: "2 Trishakti Marg", email: "-", phone: "-" },
  { id: 6, name: "132 Collins", address: ",", email: "-", phone: "-" },
  { id: 7, name: "24 Locks", address: "-", email: "-", phone: "-" },
  { id: 8, name: "7 Eleven", address: "Australia", email: "-", phone: "-" },
  { id: 9, name: "7-Eleven", address: ", f", email: "-", phone: "-" },
  { id: 10, name: "9876543210", address: ",", email: "-", phone: "-" },
  {
    id: 11,
    name: "A C Wall & Sons Plumbing",
    address: "76 Usher Avenue, Australia",
    email: "-",
    phone: "-",
  },
  {
    id: 12,
    name: "A Gift Worth Giving",
    address: "Australia",
    email: "-",
    phone: "-",
  },
  {
    id: 13,
    name: "A Grade Tree Service",
    address: "131 Osbourne drive, Australia",
    email: "-",
    phone: "-",
  },
  {
    id: 14,
    name: "A One Asphalt",
    address: "PO Box 452, Australia",
    email: "-",
    phone: "-",
  },
  {
    id: 15,
    name: "A Plant Hire",
    address: "40 Cairns Street, Australia",
    email: "-",
    phone: "-",
  },
];
